/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Hernan Medina
 */
public class RegistroEquipoGUI extends javax.swing.JFrame {

    /**
     * Creates new form RegistroEquipo
     */
    public RegistroEquipoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_Equipo = new javax.swing.JLabel();
        jlb_numInvetario = new javax.swing.JLabel();
        jtf_numInventario = new javax.swing.JTextField();
        jlb_marca = new javax.swing.JLabel();
        jtf_marca_equipo = new javax.swing.JTextField();
        jlb_anioCompra = new javax.swing.JLabel();
        jtf_anioCompra = new javax.swing.JTextField();
        jbtn_registrarEquipo = new javax.swing.JButton();
        jbtn_modificar_equipo = new javax.swing.JButton();
        jBtn_buscar_Equipo = new javax.swing.JButton();
        jbtn_eliminar_equipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_equiposComputo = new javax.swing.JTable();
        jbtn_listar_Equipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Equipo");

        titulo_Equipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_Equipo.setText("Pantalla para Equipos de Computo");

        jlb_numInvetario.setText("Numero de Inventario: ");

        jlb_marca.setText("Marca del Equipo: ");

        jtf_marca_equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_marca_equipoActionPerformed(evt);
            }
        });

        jlb_anioCompra.setText("Año de Compra:");

        jbtn_registrarEquipo.setText("Registrar");

        jbtn_modificar_equipo.setText("Modificar");

        jBtn_buscar_Equipo.setText("Buscar");

        jbtn_eliminar_equipo.setText("Eliminar");

        jTable_equiposComputo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_equiposComputo);

        jbtn_listar_Equipo.setText("Listar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_registrarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_modificar_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtn_buscar_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_eliminar_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_listar_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo_Equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_numInvetario)
                                    .addComponent(jlb_marca)
                                    .addComponent(jlb_anioCompra))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_numInventario)
                                    .addComponent(jtf_marca_equipo)
                                    .addComponent(jtf_anioCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo_Equipo)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlb_numInvetario)
                            .addComponent(jtf_numInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_marca)
                            .addComponent(jtf_marca_equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb_anioCompra)
                            .addComponent(jtf_anioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_registrarEquipo)
                    .addComponent(jbtn_modificar_equipo)
                    .addComponent(jBtn_buscar_Equipo)
                    .addComponent(jbtn_eliminar_equipo)
                    .addComponent(jbtn_listar_Equipo))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_marca_equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_marca_equipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_marca_equipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEquipoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEquipoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtn_buscar_Equipo;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_equiposComputo;
    public javax.swing.JButton jbtn_eliminar_equipo;
    public javax.swing.JButton jbtn_listar_Equipo;
    public javax.swing.JButton jbtn_modificar_equipo;
    public javax.swing.JButton jbtn_registrarEquipo;
    public javax.swing.JLabel jlb_anioCompra;
    public javax.swing.JLabel jlb_marca;
    public javax.swing.JLabel jlb_numInvetario;
    public javax.swing.JTextField jtf_anioCompra;
    public javax.swing.JTextField jtf_marca_equipo;
    public javax.swing.JTextField jtf_numInventario;
    private javax.swing.JLabel titulo_Equipo;
    // End of variables declaration//GEN-END:variables
}
